version: '3.8'
services:
  user-service:
    build:
      context: ./services/user_management
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=zubaschool
    volumes:
      - ./services/user_management:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: